[build]
  command = "pip install -r requirements.txt && python -m flask --app app run"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 